### ISSUE TITLE
i dont have write access so i cant merge the pull request

### ISSUE THREAD

**Issue by theMkeyholder** [Yoreni/Ultimate-Incremental#3]
even if im a collaborator i still cant do it

**Comment by Yoreni** [comment]
but on the github suport it says you can
https://help.github.com/en/articles/permission-levels-for-a-user-account-repository#collaborator-access-on-a-repository-owned-by-a-user-account

**Comment by Yoreni** [comment]
added another comit generators look nicer and tried to learn this vue.js thing

**Comment by theMkeyholder** [comment]
![image](https://user-images.githubusercontent.com/51534449/59227205-c2c27f00-8ba2-11e9-808f-66b2fe35d805.png)

**Comment by Yoreni** [comment]
but you just magage to edit the main.js file though so i think it is working?
