### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by Yoreni** [Yoreni/Ultimate-Incremental#9]
what does it mean when the game is in alpha or beta? what would have to happen to the game to get the game froom alpha to beta or gamma,delta,epsilon ect?

**Comment by theMkeyholder** [comment]
After v9 alpha,it goes into beta, then I planned it to be v1 afterwards, but we could just switch to gamma, delta etc. after v9 beta

**Comment by Yoreni** [comment]
i would prefer to switch to gamma,delta ect because it would be cool to go through the letters but if you dont want to do that then we wont

**Comment by theMkeyholder** [comment]
ok then we will
